name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  warmup:
    name: Warm up pkg.go.dev
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Warm up pkg.go.dev
        uses: andrewslotin/go-proxy-pull-action@master

  pages:
    name: Pages
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: go build -ldflags="-s -w" -v -o go-mlog.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      - name: Prepare deploymnet
        run: mkdir pages && cp go-mlog.wasm pages/ && cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" pages/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages